language: ruby
rvm:
- 2.2.3
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: VTWFys5SiEcKcXmcwrYxfkYQ8MnZdwBcjneu91mwwV0Cg0kCWKJJXOVxsOL91r9F1QFmgKmMhoSOnh43a4JBPqPmRgGxWH56HhoDKqsgVid/2ZQJNjpBwrG1KgJRXLbl3m4oNE4OVM9rIcYoycKbPXeGBncus2qhH7EMYuICFT/T0ZzE3aExjN1r3E64x8JQ2hIojgo3TgWnvBkRe2dpvYlJAcoP7OVNAo5eLmgX2iOrVlOICm353hYULihhrD9YhDCMlEBmptHrthVPgCUWZWW2f01zcY5EyL/LzILt301gR6woPFQsTNvNNInUNTdurRjurXmMzvKcjhz1u1u6g+XtbCDH2YTlmDnJGy546iJgxcK1WpNn5i9HfMg5JSOl1LdNNIDlR0xY9owKOmMDOLt39kO/jCEhGEDRZCM8Vvs9lflbYRop88q+Fqv0J0NWZ5P7OwlN5lnxuCHApH1HGw+MVRvK+HqQtKfYuvU/n9ZPLTnPDc70cgW3vATd5xGNpugP7qQIafDinvz5smM42UK1NRNRKCvmlMCqzmCqFIsnedX7nuvEzfnScGmh6rOwUYII0nnjJWV2mBIzzEDly4muWzzsRUtKaojAturK55iJw7Ga5SrQP4eH4VfYGV65fYIlv7qiKeUw6nnBxrTt7Z7+iGzLIPQLNTd+JjXXmnI=
  app: limitless-plains-5091
run:
    - "rake db:migrate"
    - "rake cleanup"
