language: ruby
rvm:
- 2.2.3
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: m3NRqgW0MY9bEZ3/ljVppX1Yw5fEQIJfxiF+qNpWyAi8fofUcafEPYcAXE7v5UyVenJ+GZPByfgxeRBoPGB4MB2JV4H04Htr5J6ZzPrhtZq9mD5aPlefDlc1OoMgvH0106h9T4XH6yloCjzICD7rL2S4jAD06Ud0gs001Chbjqm+V+IifxgMcqTOGC552qYP5qHxnNPA4rA3rjAPn6V42ulbjlHDJsRi7v8TId0cuGBH6aneeoUdvu8jSL0DGUDkLEmCoMWzkPeVqN4q4+CPj+IclSQJIyAk7zw3INz51ubapPiCNH4QvTjOZxza5Km6zIAaHefaODLTfVQ3wEQPDmf2nTUcSMganVlVFt5wuREmqzOB8lQoclizR7xY2aH7gluRL9XurkfoeDqdhPJLDfv7iqXSbyiG4fxRbaswoMapkJzOfrOfqnqyr8mqs9QowXTxMPvunrdIy4qWvB1dJvAz1a50Byz7SSg9WxR8LEDaHj8b3qxzEC9F5hhSfgtjCmiWuAdx5k7y5szqqyR8UOXI2szp1VgUBYj1gLJlXh9yOH84/WVXsYxK4rkWpwb2iEthK5Pfnsmntmfj9G3wH9ICIYCvJbmMm+0wb8j0N6ZkV85NZ/b6WiRy5ZCpzQtxhTjFIW3JUHEnTf4OXJZT5/dS1tfvlE1HsaOg7HlMhGA=
  app: limitless-plains-5091
  on:
    repo: cekcbj/twitterclone
